language: cpp

services:
  - docker

branches:
  only:
    - master

env:
  - DOCKER_IMAGE=knapsu/plex-media-player-flatpak:bionic

before_script:
  - echo "${DOCKER_TOKEN}" | docker login --username knapsu --password-stdin
  - docker pull "${DOCKER_IMAGE}"
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in keys/id_rsa.enc -out keys/id_rsa -d
  - chmod go-rwx keys/id_rsa
  - openssl aes-256-cbc -K $encrypted_e877c2da948d_key -iv $encrypted_e877c2da948d_iv -in keys/pgp-flatpak.asc.enc -out keys/pgp-flatpak.asc -d

script:
  - env | grep -E "^TRAVIS|^DOCKER|^PLEX" > travis.env
  - docker run -t -d --volume ${TRAVIS_BUILD_DIR}:/plex --workdir /plex --env-file travis.env --name builder --device /dev/fuse --privileged ${DOCKER_IMAGE}
  - docker exec -t builder ./scripts/build.sh
  - ./scripts/repo.sh --download
  - docker exec -t builder ./scripts/export.sh
  - ./scripts/repo.sh --upload

after_script:
  - docker stop builder

cache:
  directories:
  - flatpak-builder
  - repo
