name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'docker/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: knapsu/plex-media-player-flatpak:focal
      options: --privileged --device /dev/fuse
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache data
        uses: actions/cache@v2
        with:
          key: flatpak-cache
          path: ~/flatpak-builder
      - name: Run build script
        run: ./scripts/build.sh
