name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'docker/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: knapsu/plex-media-player-flatpak:focal
      options: --privileged --device /dev/fuse
    env:
      UPLOAD_USER: ${{ secrets.UPLOAD_USER }}
      UPLOAD_SERVER: ${{ secrets.UPLOAD_SERVER }}
      UPLOAD_PATH: ${{ secrets.UPLOAD_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.UPLOAD_SERVER }}
      - name: Cache data
        uses: actions/cache@v2
        with:
          key: flatpak-cache
          path: ~/flatpak-builder
      - name: Run build script
        run: ./scripts/build.sh
      - name: Sync Flatpak repository
        run: ./scripts/repo.sh --download
