name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'docker/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: knapsu/plex-media-player-flatpak:focal
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build script
        run: ./scripts/build.sh
