name: Docker
on: push
jobs:
  build:
    name: Build
    container: knapsu/plex-media-player-flatpak:bionic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build script
        run: ./scripts/build.sh
